# Basic
motd=Eaglercraft Server on Railway
online-mode=false
enforce-secure-profile=false

# Network
server-ip=0.0.0.0
server-port=${PORT}

# Performance (important for Railway)
view-distance=6
simulation-distance=4
max-players=10

# World
level-name=world
gamemode=survival
difficulty=easy
pvp=true

# Spawn
spawn-protection=0

# Misc
allow-flight=true
max-tick-time=60000
enable-command-block=false

# Logging / Debug
enable-status=true
enable-query=false
